### ISSUE TITLE
CORS problem with access

### ISSUE THREAD

**Issue by twinfire** [s1n4/leptus#33]
We are currently using leptus as a restful web service and are encountering problems with access from jquery on a different domain.  We have added the cross_domains callback as follows:

cross_domains(_Route, _Req, State) ->
   {['_'], State}.

and are still seeing the error from the client.  Here is how we are calling the url from the client:

```
$.ajax({url:url1, type: 'get',success:function(result) {
    alert("yay!");
}});
```

Are we supposed to add any other callbacks or doing anything else?  Any help would be greatly appreciated.

Thanks.

Geoff

**Comment by tommyjcarpenter** [comment]
How do you enable CORS support that depends on the Port too? I.e., how do you configure leptus to return the header `Access-Control-Allow-Origin: *`?
