### ISSUE TITLE
Cross domain Origin header problem with advanced rest client extension

### ISSUE THREAD

**Issue by twinfire** [s1n4/leptus#37]
I am encountering an issue with the cross_domain functionality when testing from the "advanced rest client" chrome extension.  When I attempt to POST a request to a leptus route, a Server 500 is returned and it appears to be caused by the "Origin: chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo" header in the request.  Using curl, I have verified that if I change the value of the Origin header to a valid url (or anything without a "chrome://" in it) it works fine.  I believe the spec states that a client shouldn't modify the origin header.  Is this a bug with leptus or a bug with the advanced rest client?  I am considering modifying leptus to allow this but wanted to get your feelings on it first.

**Comment by s1n4** [comment]
Thank you for reporting this!

I believe that it is a bug with leptus. I will be grateful for a patch.

Thanks again!

**Comment by s1n4** [comment]
I recently pushed a commit (https://github.com/s1n4/leptus/commit/97151bae1567d2a4bc728fbf6e10a0798179645f) that's supposed to fix this issue.
