### ISSUE TITLE
Do not use leptus_handler:console_log/2

### ISSUE THREAD

**Issue by ates** [s1n4/leptus#40]
Is there is any way to disable or remove usage of console_log/2 function for each request?

**Comment by s1n4** [comment]
Alright. I will make it optional or I will probably remove it because Access Log's been existing.

**Comment by s1n4** [comment]
Here you go https://github.com/s1n4/leptus/commit/7143046376832d7fdfacba484efde449a0e6675d.

The master branch now provides the functionality to make that kinda log optional.
All you need to do is add the `leptus_debug_log` log handler with your custom format or the default one.
So, for example, you can pass the following option to `leptus:start_listener/3`:
``` erlang
Opts = [{log_handlers, [{leptus_debug_log, default}]}],
leptus:start_listener(http, [...], Opts).
```

It will be documented as soon as possible.

Thank you!

**Comment by s1n4** [comment]
Oh, I forgot to mention that console log is disabled by default (in the master branch), and if you need it, you can use the example above.

**Comment by ates** [comment]
Thanks a lot
