### ISSUE TITLE
erlang r18 not supported

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [s1n4/leptus#47]
when i git clone, make, it told me "erlang r18 not supported"

**Comment by ates** [comment]
@s1n4 Please update msgpack in rebar.config

**Comment by ziyouchutuwenwu** [comment]
i update with the msgpack with 0.3.4

**Comment by s1n4** [comment]
Which version of msgpack works the best for you?

**Comment by ates** [comment]
As for me, it's does not matter, I suppose to use the latest. Or at least the version where was fixed limitation from erlang 17

**Comment by ates** [comment]
Is it possible to make msgpack optional in the same manner as jiffy or jsx?

**Comment by s1n4** [comment]
Yeah, it is. And I will be grateful for a pull-request.

**Comment by ziyouchutuwenwu** [comment]
0.3.5 seems to work with r18
