### ISSUE TITLE
issue at start

### ISSUE THREAD

**Issue by dubrovine** [s1n4/leptus#57]
Hello. I'm kinda new to erlang and trying to make simple rest api
so i found the Leptus :)

i have already compiled the app via rebar3 and now I getting the errors

1> leptus:start_listener(http, [{'_', [{hello, undefined_state}]}]).
** exception error: undefined function hello:routes/0
     in function  leptus_router:'-handle_routes/2-fun-0-'/2 (c:/restapi/_build/default/lib/leptus/src/leptus_router.erl, line 94)
     in call from lists:foldl/3 (lists.erl, line 1263)
     in call from leptus_router:handle_routes/2 (c:/restapi/_build/default/lib/leptus/src/leptus_router.erl, line 96)
     in call from leptus:start_listener/4 (c:/restapi/_build/default/lib/leptus/src/leptus.erl, line 96)

could you please tell me where I turned the wrong way? thx in advance

**Comment by s1n4** [comment]
Hello,

Maybe you didn't add this to your module:
```
-compile({parse_transform, leptus_pt}).
```

**Comment by dubrovine** [comment]
added. I am using your Quick example for testing

**Comment by dubrovine** [comment]
sorry, figured out.
I forgot to change 'hello' to my currest app name.

thx :)

**Comment by momomo** [comment]
@dubrovine can you send me an email to ceo ATT momomo DOTT com? I would like to discuss an oppurtonity.
